### ISSUE TITLE
Добавить класс для работы со страницами

### ISSUE THREAD

**Issue by olegKa** [LevButkovskiy/CompasPlus#1]
Класс должен наследоваться от NSObject
Класс должен уметь хранить количество записей на странице, количество страниц с данными, номер текущей страницы.
Реализовать инициализатор класса данными из ответа hh по аналогии с компаниями.
Реализовать инициализатор класса с параметром <записей на странице>. Возможно, что нам понадобится получать не по 20, а по 10 или 50 записей.
Реализовать метод для nextPage, который будет инкрементировать текущий номер страницы. Этот метод позволит нам использовать данный класс в запросе на сервер для получения следующей страницы.

**Comment by LevButkovskiy** [comment]
v.1.3
Пытаюсь сделать :
Реализовать инициализатор класса с параметром <записей на странице>. Возможно, что нам понадобится получать не по 20, а по 10 или 50 записей.
 Через присваивание 
[json setValue:thisPage forKey:@"page"];
значение не присваивается, или по другому надо?
Остальное вроде готово

**Comment by olegKa** [comment]
Несмотря на комментарии, не понял, зачем этот код:
`pages.nextPage; //incrementing number of page
    NSLog(@"numberThisPage: <%@>", pages.numberThisPage);
    NSNumber *thisPage = [json objectForKey:@"page"]; //thisPage - number of this page in json
    thisPage = pages.numberThisPage; //this page - incremented value of page number in json
    [json setValue:thisPage forKey:@"page"]; //check set value for json
    NSArray *items = [json objectForKey:@"items"];`

Экземпляр класса BLPages (на самом деле это одна страница, поэтому правильнее было бы BPPage) нужен нам в ViewController для понимания, где мы сейчас находимся в длинном списке компаний. Поэтому нужно задекларировать переменную под него в классе ViewController.

> [json setValue:thisPage forKey:@"page"];
нельзя менять содержание немутабельного объекта после того, как он уже сформирован.
