### ISSUE TITLE
Разработка сервиса запроса данных

### ISSUE THREAD

**Issue by olegKa** [LevButkovskiy/CompasPlus#2]
Задача: разработать класс-синглтон, который умеет делать запросы на сервер hh (то, что у нас сейчас во ViewContrloller делает метод requestData).

Этап 1:
Разобраться с понятием синглтона в ios. 
Сделать простейший синглтон-класс DataManager.

**Comment by olegKa** [comment]
Вот этот код:

[session requestDataForType:@"employers" onPage:@(0) perPage:@(20)];
NSDictionary *json = session.res_json;

работать не будет, потому-что в requestDataForType используется асинхронный доступ к серверу. Это значит, что после вызова requestDataForType сразу выполняется json = session.res_json без ожидания результата запроса к серверу. Поэтому json всегда будет nil, ведь session.res_json неизвестно когда заполнится.

Нам нужно каким-то образом после вызова self.res_json = json внутри requestDataForType дать знать нашему коду, что получены новые данные и их нужно обработать. Для этого можно использовать блок или делегирование. Мы остановились на блоке. 

Блок - это функция с параметрами или без них и как любая функция ее нужно вызывать, сама она себя не вызовет. Нужно, чтобы вызывалось что-то вроде requestCompletion(json) и "ловилось" в нашем модуле  viewController.

Блок можно передавать в наш requestDataForType как параметр, такой же как type, page, perPage. Назовем его completion, например. 
- (void)requestDataForType:(NSString *)type onPage:(NSNumber *)page perPage:(NSNumber *)perPage completion:(<описание_блока>)completion

Я не указал тип параметра - ты должен описать этот тип так, чтобы компилятор понял, что это блок, который вызывается с параметрами NSDictionary *json и NSError *error

Потом нужно вызвать этот блок после присвоения self.res_json = json.

Ну и по итогу нужно переписать вызов нашего модернизированного метода requestDataForType с учетом того, что будет обрабатываться блок.

**Comment by LevButkovskiy** [comment]
Можете версию 1.7.2 посмотреть
Я во ViewContoller создал блок и передаю его в requestDataForType и дальше не понимаю что в блоке делать нужно
